### ISSUE TITLE
Getting: "TypeError: ... is not a constructor" when using e.g. InlineCheckout in a react web app

### ISSUE THREAD

**Issue by mysil2** [bambora/checkout-sdk-web#1] opened 2018-03-12 12:28 UTC
I'm trying to use this SDK in a react application. When following the documentation using this code:
```
import { InlineCheckout, Event } from "@bambora/checkout-sdk-web";

const checkout = new InlineCheckout(
  "<<YOUR-SESSION-TOKEN-HERE>>",
  {
    container: document.body
    // For this example, we put the iframe in the body element.
  }
);

checkout.on(
  Event.Authorize,
  payload => console.log(payload.data.txnid)
  // The transaction ID is logged to the console upon authorize.
);
```
I get the following error:

> TypeError: __WEBPACK_IMPORTED_MODULE_3__bambora_checkout_sdk_web__.InlineCheckout is not a constructor

I tried both version 1.0.1 and 2.0.0. Also I started a fresh project with create-react-app to check if there was any problems with my project. Do you have any idea how I can get it to work. Could it be something when integrated with Webpack or any other configuration in a React web app context?

**Comment by jesperzach** [comment] 2018-03-12 12:36
Which version of Webpack, NPM, and Node are you using @mysil2 ?
I'll look into it straight away.

**Comment by mysil2** [comment] 2018-03-12 12:44
I think both projects are using NPM 5.71, Node 9.7.1. The create-react-app has the configuration hidden if you don't eject it, but according to the error message it is 3.x.x. My main project uses Webpack 2.5.1.

**Comment by jesperzach** [comment] 2018-03-12 14:45
The issue is due to using the IIFE setting, when bundling with Rollup, and referencing the output IIFE script in the `browser` property in `package.json`.
Per default, Webpack prioritizes the `browser` property, then `module`, and finally `main`.
I'll have a fix ready soon. Sorry for the inconvenience and thanks for the report!

**Comment by jesperzach** [comment] 2018-03-12 15:29
https://github.com/bambora/checkout-sdk-web/commit/1e2a5873a0f3aaf412f7100f7190845c71f4eac5 Version 3.0.0 is out with proper Webpack support.
Closing...

**Closed by jesperzach** 2018-03-12 15:29 UTC
Labels: bug

**Comment by mysil2** [comment] 2018-03-13 08:14
Thanks for your fast responses and fix!
